# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/demoColorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 145)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonColor = QtWidgets.QPushButton(Dialog)
        self.pushButtonColor.setObjectName("pushButtonColor")
        self.horizontalLayout.addWidget(self.pushButtonColor)
        self.frameColor = QtWidgets.QFrame(Dialog)
        self.frameColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColor.setObjectName("frameColor")
        self.horizontalLayout.addWidget(self.frameColor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButtonCopy = QtWidgets.QPushButton(Dialog)
        self.pushButtonCopy.setEnabled(False)
        self.pushButtonCopy.setText("")
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.verticalLayout.addWidget(self.pushButtonCopy)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonColor.setText(_translate("Dialog", "Choose Color"))
