# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/server.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEditmessage = QtWidgets.QTextEdit(Dialog)
        self.textEditmessage.setObjectName("textEditmessage")
        self.verticalLayout.addWidget(self.textEditmessage)
        self.lineEditmessage = QtWidgets.QLineEdit(Dialog)
        self.lineEditmessage.setObjectName("lineEditmessage")
        self.verticalLayout.addWidget(self.lineEditmessage)
        self.sendButton = QtWidgets.QPushButton(Dialog)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout.addWidget(self.sendButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "server"))
        self.sendButton.setText(_translate("Dialog", "Send"))
